### ISSUE TITLE
nodeenv --list returns error

### ISSUE THREAD

**Issue by waldronj** [ekalinin/nodeenv#119]
Currently have a fresh install of nodeenv 0.13.0, running the command `nodeenv --list` returns the following: 
> error: Traceback (most recent call last):
>  File "/usr/local/bin/nodeenv", line 9, in <module>
>    load_entry_point('nodeenv==0.13.0', 'console_scripts', 'nodeenv')()
>  File "/Library/Python/2.7/site-packages/nodeenv.py", line 820, in main
>    print_node_versions()
>  File "/Library/Python/2.7/site-packages/nodeenv.py", line 734, in print_node_versions
>    versions = get_node_versions()
>  File "/Library/Python/2.7/site-packages/nodeenv.py", line 727, in get_node_versions
>    return [v.public for v in sorted_versions]
>AttributeError: 'tuple' object has no attribute 'public'

I have confirmed that this only occurs on my Mac with version 0.13.0, I went back and pip installed 0.12.3.

**Comment by waldronj** [comment]
Further investigation shows that the line in question has been removed from the code in the current master branch. Installing from source, I can't replicate this issue.

**Comment by ekalinin** [comment]
Hi @waldronj .Thanks for report.

Seems, it very similar to #117 #118.
Will release a new version today.

**Comment by ekalinin** [comment]
Please, test version 0.13.1

**Comment by ekalinin** [comment]
Fixed in #117 #118.
