### ISSUE TITLE
nodeenv hangs when setting up a new environment

### ISSUE THREAD

**Issue by gduverger** [ekalinin/nodeenv#120]
I tried using `nodeenv` in the following way:

    $ virtualenv --python=python2.7 venv
    $ source venv/bin/activate
    (venv) $ pip2.7 install nodeenv
    (venv) $ nodeenv --node=0.12.2 nenv

But it hangs on:

     * Install node (0.12.2)..

I am not sure how to investigate this issue. Thoughts? Do I need to install Node before all that (currently, `$ node \ -sh: node: command not found`)? I was under the impression that the correct version of Node would be installed by `nodeenv`.

**Comment by ekalinin** [comment]
Hi @gduverger 
1. Please, try option ``--verbose`` and show output
2. It would be faster if you'll use option ``--prebuilt``

**Comment by gduverger** [comment]
@ekalinin Maybe it *was* a speed issue. Using `--verbose` made it clearer what was being processed. It seems to work now. Thanks, @ekalinin.

**Comment by ekalinin** [comment]
Glad to hear that it works for you.
No problems.
