### ISSUE TITLE
Encoding not specified in setup.py

### ISSUE THREAD

**Issue by sirmar** [ekalinin/nodeenv#123]
When installing nodeenv through bamboo it get this:

15-May-2015 11:14:52	    Traceback (most recent call last):
15-May-2015 11:14:52	      File "<string>", line 20, in <module>
15-May-2015 11:14:52	      File "/tmp/pip-build-_gpsu3pm/nodeenv/setup.py", line 20, in <module>
15-May-2015 11:14:52	        ldesc = read_file('README.rst')
15-May-2015 11:14:52	      File "/tmp/pip-build-_gpsu3pm/nodeenv/setup.py", line 18, in read_file
15-May-2015 11:14:52	        ).read()
15-May-2015 11:14:52	      File "/bamboo/xml-data/build-dir/PIT-DE-TEST/.tox/ci/lib/python3.4/encodings/ascii.py", line 26, in decode
15-May-2015 11:14:52	        return codecs.ascii_decode(input, self.errors)[0]
15-May-2015 11:14:52	    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7085: ordinal not in range(128)

**Comment by asottile** [comment]
Would love a release with this, it's breaking my travis builds: https://travis-ci.org/asottile/css-explore/jobs/62762793

**Comment by sirmar** [comment]
We found a workaround to be to set LANG environment variable to something utf-8-ish inside tox.

So in tox.ini:

[testenv]
setenv =
    LANG=en_US.UTF-8

Give it a try.

/Marcus

**Comment by ekalinin** [comment]
> We found a workaround to be to set LANG environment variable to something utf-8-ish inside tox.

Thanks! Done.

**Comment by asottile** [comment]
So the root cause is tox no longer passes through environment variables by default.  I've created https://bitbucket.org/hpk42/tox/issue/247/pass-through-lang-environment-variable-by

I think the more-correct patch is to passenv LANG instead of explicitly setting it in tox

**Comment by homeworkprod** [comment]
@asottile, thanks for creating the ticket.

FTR, I came across this as the installation of the Arrow package (v0.5.4) fails on my CI like this (because of some Korean symbols in the README):
```
Collecting Arrow>=0.4.4 (from -r requirements.txt (line 13))
  Downloading arrow-0.5.4.tar.gz (81kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-41rzo0k_/Arrow/setup.py", line 31, in <module>
        long_description=open('README.rst').read(),
      File "/fooooo/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2974: ordinal not in range(128)
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-41rzo0k_/Arrow
```

Tox itself is invoked with `LANG=C.UTF-8 tox` (and the locale `C-UTF-8` is present).

**Comment by ekalinin** [comment]
> So the root cause is tox no longer passes through environment variables by default.  I've created https://bitbucket.org/hpk42/tox/issue/247/pass-through-lang-environment-variable-by
> I think the more-correct patch is to passenv LANG instead of explicitly setting it in tox

Thanks!
