### ISSUE TITLE
Launchpad PPA packaging

### ISSUE THREAD

**Issue by sgnn7** [ekalinin/nodeenv#126]
@ekalinin Created a Launchpad project for daily builds of this project:
https://code.launchpad.net/~sgnn7/+archive/ubuntu/nodeenv

Sadly 2 problems here:
- https://bugs.launchpad.net/bzr-builder/+bug/1432282. Since `debian-upstream` is in same branch and I can't rename the dir in a recipe, I need separate branch/repo for the packaging. I created my own at https://github.com/sgnn7/nodeenv-launchpad-packaging but having a `debian` branch or moving the folder `debian-upstream` to `debian` would be better since the current way requires manual pushes to update the packaging.
- Only 0.8+ `dh-virtualenv` packages on Launchpad are for Trusty/Utopic but I can only specify Trusty as the target so only one distribution build. This would require builing for ther distro versions by the owners of that PPA.

Let me know if you want something else done with this.

**Comment by jhermann** [comment]
The current name was in response to Debian maintainers *not* wanting a `debian` dir in their way. Can't you just symlink it?! (If not, my opinion about Launchpad would sink even lower)

**Comment by sgnn7** [comment]
@jhermann Pretty much no file ops can be done on the same filesystem of the branch itself (https://help.launchpad.net/Packaging/SourceBuilds/Recipes). Can the packaging be copied (or moved) to a `debian` git branch in this repo? 

PS: Yeah, the Launchpad stuff is pretty horrendous to use - I spent about 4hrs trying to get this relatively simple package to build on it yesterday.

**Comment by asottile** [comment]
fwiw, nodeenv has been packaged for debian and is available in 16.04: https://github.com/chriskuehl/nodeenv

**Comment by sgnn7** [comment]
@asottile True. Closing as resolved I suppose.
