### ISSUE TITLE
It get stuck installing node

### ISSUE THREAD

**Issue by mayuroks** [ekalinin/nodeenv#133]
I have recently tried it and it gets stuck at installing node.

```
$ nodeenv mynodeapp -v
Installing node 4.0.0....

## Gets stuck here for a long time ##
```

Any fix for this. I am using OSX Yosemite.

**Comment by ekalinin** [comment]
Hi @mayuroks 

Thanks for report.

Would you be able to provide more details?
I didn't get any issues:
```
➥ virtualenv testenv
➥ . testenv/bin/activate
(testenv) ➥ pip install nodeenv
(testenv) ➥ nodeenv --version
0.13.6
(testenv) ➥ nodeenv -p --prebuilt
 * Install node (4.0.0)... done.
 * Appending data to ~/Projects/nodeenv/testenv/bin/activate
(testenv) ➥ node -v
v4.0.0
```

**Comment by ekalinin** [comment]
Seems, it's ok.

**Comment by mayuroks** [comment]
Sorry for delayed reply.
**But I am still seeing this issue even after following your steps**. Any tips to debug.

**Comment by ekalinin** [comment]
> But I am still seeing this issue even after following your steps. Any tips to debug.

If you run it like this `nodeenv -v <env-name>` then you compiling node from source.
Try to install it like i showed earlier: `nodeenv --prebuilt mynodeapp`
And, please, next time show full logs (like i did).
It would be much easier to understand whats happened.

**Comment by ekalinin** [comment]
Still no response. Seems, all is good.
