### ISSUE TITLE
global installation breaks python's virtualenv

### ISSUE THREAD

**Issue by ovanes** [ekalinin/nodeenv#135]
Installed nodeenv globally and it broke at least my freeze command. Any python virtualenv now prints node packages and errors!

Trying to remove it (pip remove nodeenv) does not help... How to cleanly remove this package from the system.

And please fix the docs, that it installing it globally will break python virtualenv => therefore installing it in the virtualenv is the suggested scenario.

**Comment by ekalinin** [comment]
Hi, would you be able to provide an example? 
As I remember for python you need to do 'pip freeze' to show installed packages
and nodeenv just overrides function 'freeze'.

**Comment by ovanes** [comment]
Yes, you are right... Worked to much :( and somehow forgot about pip. But anyway, that is somehow strange that using pip remove nodeenv I still able to call `freeze`. I think it might be more clear to avoid such misleadings to call `nodeenv freeze` instead of `freeze`.

**Comment by ekalinin** [comment]
> I think it might be more clear to avoid such misleadings to call nodeenv freeze instead of freeze.

Yeah, seems, it make sense.
