### ISSUE TITLE
on windows

### ISSUE THREAD

**Issue by msangel** [ekalinin/nodeenv#147]
First problem was encoding, so I replace 

    line = line.decode('utf-8').rstrip()

with:

    codecs=['utf8', 'cp1252']
        for i in codecs:
            try:
                line = line.decode(i).rstrip()
            except:
                pass

But I have no idea what to do with this:
    OSError: Command ./configure "--prefix='C:\programs\nodevenv\env'" failed with error code 1

Any help?)

**Comment by techtonik** [comment]
Duplicate of #140. But I am not sure what encoding error did you get. Python 3?

**Comment by ekalinin** [comment]
Will be fixed in #140
