### ISSUE TITLE
Suggest that setting `src_domain` an alternative option

### ISSUE THREAD

**Issue by subcrew** [ekalinin/nodeenv#157]
For some reason as we all know, it will be really slow(even network error) to download nodejs from `nodejs.org` in China. So I suggest that treating `src_domain` as an alternative option in cmd to get better
UX.

Such as:

```
nodeenv fkgfw --domain=npm.taobao.org/mirrors/node
```

**Comment by ekalinin** [comment]
Fixed in #208
