### ISSUE TITLE
Python2 and Python3 support

### ISSUE THREAD

**Issue by eirnym** [ekalinin/nodeenv#164]
Please, specify in categories if you support Python 2 and/or Python 3

**Comment by amureki** [comment]
@eirnym you can see in [README](https://github.com/ekalinin/nodeenv/blob/master/README.rst) that only Python 2.6/2.7 supported.

I'm running this on Python 3 and it is kinda working, but spamming print syntax errors.

**Comment by eirnym** [comment]
@amureki I need this in `setup.py`

**Comment by eirnym** [comment]
FYI: https://github.com/nodejs/node/issues/133#issuecomment-75736337
