### ISSUE TITLE
Are nodeenvs cp-safe

### ISSUE THREAD

**Issue by snakescott** [ekalinin/nodeenv#166]
Sorry in advance if this is obvious, clearly documented, or if this is the wrong forum for this question. I made sure to review the repo README, check for a mailing list, and Google before filing.

Is it safe to copy an nodeenv via "cp -r old_nodeenv_dir new_nodeenv_dir"? Or, for example, is this not the case due to absolute paths inside the nodeenv.

See e.g. http://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html#cpvirtualenv

Thanks!

**Comment by ekalinin** [comment]
Hey @snakescott 

No, it's not safe. Currently, all paths are hard coded in the `activate` script.
So, it's safer to create a new environment.

**Comment by snakescott** [comment]
Thanks for the info! 

Quick followup -- would nodeenvs created with -p be safe to copy with cpvirtualenv?

**Comment by ekalinin** [comment]
> would nodeenvs created with -p be safe to copy with cpvirtualenv

You may try, but I'm not sure ;)
