### ISSUE TITLE
"failed to create process" response when trying to use nodeenv (Windows 10)

### ISSUE THREAD

**Issue by nickbarry** [ekalinin/nodeenv#170]
Hey, I've just installed nodeenv globally with pip. Now I'm trying to run it, and whenever I run something like `nodeenv test` or just `nodeenv`, I get this response: "failed to create process". 

Googling 'nodeenv "failed to create process"' comes up with zero results. Likewise searching the exact string "failed to create process" in this repo's issues/questions/etc.

Does anyone know what's up, or how I might debug this issue?

I'm on Windows 10.

**Comment by ekalinin** [comment]
Hey @nickbarry 

Thanks for report.
I've just released 1.0 version.
Please, try it.

PS: unfortunately `nodeenv` doesn't fully supports windows at the moment.

**Comment by ekalinin** [comment]
Should be fixed in #173
