### ISSUE TITLE
nodeenv try to download non existing tar.gz prebuilt under Cygwin

### ISSUE THREAD

**Issue by Lucas-C** [ekalinin/nodeenv#178]
Hi,

I think this project used to support Cygwin, is this still the case ?

I'm having an issue with the following command:
```
nodeenv --prebuilt tmp
```
The error is the following:
```
urllib2.HTTPError: HTTP Error 404: Not Found
```
The `tar.gz` it tries to install is https://nodejs.org/dist/v7.2.1/node-v7.2.1-cygwin_nt-6.1-x64.tar.gz, which does not exist. My guess is that `nodeenv` should use the Windows prebuilts instead: https://nodejs.org/dist/v7.2.1/node-v7.2.1-win-x64.zip
This is because `platform.system()` is used: https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py#L503

I faced this problem while using `pre-commit` : https://github.com/pre-commit/pre-commit/issues/455

Could `nodeenv` uses the Windows prebuilt when invoked under Cygwin ?

**Comment by ekalinin** [comment]
Hey @Lucas-C 

> I think this project used to support Cygwin, is this still the case ?

Nope. This project is not for Cygwin. Cygwin is not supported iirc:
  * https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py#L493

Why don't you want to try to install nodejs in Windows?
It should works after this patch #173 

PS: 
We can try to support Cygwin. 
What is the output of this commands in python under Cygwin?
```python
>>> import platform
>>> platform.system().lower()
```

**Comment by Lucas-C** [comment]
```
$ python -c "import platform; print(platform.system().lower())"
cygwin_nt-6.3
```

**Comment by Lucas-C** [comment]
I know that even `npm` project policy is to not support Cygwin, but I have a need to use both at work, and my team has been able to do so for the past 2 years without any major hurdle.
It would be awesome if `nodeenv` could support it too.

I have been helping on Python projects like `html5validator`, `luigi`, `pew` and `pre-commit` so that they support Cygwin, so I'd be happy to help if i can.

**Comment by techtonik** [comment]
Try installing `nodeenv` from GitHub. There are new changes that fix more compatibility issues for Windows.

**Comment by Lucas-C** [comment]
It currently does not work, but I sent a PR to add support for Cygwin:
https://github.com/ekalinin/nodeenv/pull/194

My test:
````
$ nodeenv --prebuilt env
 * Install prebuilt node (8.2.1) ..... done.
$ source env/bin/activate
```

**Comment by techtonik** [comment]
@Lucas-C why Cygwin and not MSYS2?

**Comment by Lucas-C** [comment]
Are you asking why I use Cygwin and not Msys2 ?
Mostly habits. The only comparison point I have is that I really prefer `apt-cyg` and the huge Cygwin packages collection over Msys2 `pacman`

Also, I sent and incomplete version of this PR by error, I'm sorry.
I'm going to update it later today, as soon as I get an Internet connection good enough to test resinstalling node + npm.
At the moment, with the current code, `npm install` fails under Cygwin once in the virtualenv.
Sorry about that. Fix incoming

**Comment by fczuardi** [comment]
I am having 404 errors when using pre-commit and I suspect that this is for similar reasons, I am trying to run pre-commit on a platform that might not be supported (linux, arm64). Should I file a new issue for that?

**Comment by Lucas-C** [comment]
Closing rhis as the PR has been merged
