### ISSUE TITLE
Directives in MANIFEST.in may cause pip install to fail

### ISSUE THREAD

**Issue by thunderk** [ekalinin/nodeenv#184]
In MANIFEST.in file, there are directives about a "debian" folder that is not present. In some python/setuptools configuration, this leads to an error on pip install.

Quick test in a docker:
`
$ docker run --rm -it python:3.4 pip install nodeenv
Collecting nodeenv
  Downloading nodeenv-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/nodeenv.egg-info
    writing pip-egg-info/nodeenv.egg-info/PKG-INFO
    writing entry points to pip-egg-info/nodeenv.egg-info/entry_points.txt
    writing dependency_links to pip-egg-info/nodeenv.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/nodeenv.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/nodeenv.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/nodeenv.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    error: [Errno 2] No such file or directory: 'debian'
`

**Comment by thunderk** [comment]
Thank you for the quick fix !
But there are other lines with "debian", shouldn't they be changed too ? (prune and recursive-exclude)

**Comment by ekalinin** [comment]
Oops. Sorry. Fixed all rows :)

**Comment by thunderk** [comment]
Thanks !
Could you please make a new release with the fix ?

**Comment by ekalinin** [comment]
https://github.com/ekalinin/nodeenv/releases/tag/1.1.2

**Comment by thunderk** [comment]
Nice, thanks :)
