### ISSUE TITLE
How to disable --prompt from the CLI?

### ISSUE THREAD

**Issue by magicmark** [ekalinin/nodeenv#191]
Hi!

How can I make a nodeenv that doesn't add a prefix at all to my PS1? (I prefer to check for `$NODE_VIRTUAL_ENV` and set it myself in my theme)

Setting `--prefix ''` defaults to (nenv)

thanks!

**Comment by ealap** [comment]
if anyone else still needs an answer to this, set the following env variable to 1 before activating the environment
```
NODE_VIRTUAL_ENV_DISABLE_PROMPT=1
```
