### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by tspmelo** [ekalinin/nodeenv#217]
Hi,
would it be possible to known when the next release is due?

Currently, over at ceph, we are having problems on arm64, related to nodeenv, and the fix is already in master.
We would like to keep the installation of nodeenv via pip, but we are wondering if we should wait for the next release. Alternatively we would need to change how we install nodeenv.

Thoughts?

**Comment by ekalinin** [comment]
Hi,

https://github.com/ekalinin/nodeenv/releases/tag/1.3.1
