### ISSUE TITLE
"Could not find a version" error while installing

### ISSUE THREAD

**Issue by marchrius** [ekalinin/nodeenv#218]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request
* [ ] question about the decisions made in the repository

### Issue description

**Current behavior:**
Fail to install the nodeenv package with command
`sudo pip install nodeenv`

The error reported is:
```
Collecting nodeenv
  Could not fetch URL https://pypi.python.org/simple/nodeenv/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement nodeenv (from versions: )
No matching distribution found for nodeenv
```

**Expected behavior:**
Install the package

**Steps to reproduce:**
pip install nodeenv

**Related code:**

### Other information:

**python, OS, shell**
- PIP: `pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)`
- OS: macOS Sierra `16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64`
- SHELL: `zsh 5.2 (x86_64-apple-darwin16.0)`

**Comment by ekalinin** [comment]
Hi,

Thanks for report.
Just tried to reproduce it on OSX:

```
➜ virtualenv env
➜ . env/bin/activate
➜ pip install nodeenv
Collecting nodeenv
  Downloading https://files.pythonhosted.org/packages/e0/89/dbda906ff83360c3fe33d5d11102c39036614ee8ef943317a95cbe691136/nodeenv-1.3.1.tar.gz
...
Successfully built nodeenv
Installing collected packages: nodeenv
Successfully installed nodeenv-1.3.1
➜ pip freeze | grep node
nodeenv==1.3.1
➜ pip --version
pip 10.0.1 from /tmp/env/lib/python2.7/site-packages/pip (python 2.7)
➜ zsh --version
zsh 5.2 (x86_64-apple-darwin16.0)
```

**Comment by ekalinin** [comment]
Looks like a network issue.
