### ISSUE TITLE
http error if node > 9.11.2

### ISSUE THREAD

**Issue by binooetomo** [ekalinin/nodeenv#220]
Dear All ...

My Nodeenv version is 1.3.1
nodeenv - l said the latest is 10.6.0, but `nodeenv -p -n 10.6.0` producing:

```
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```
mysistem is 32-bit ubuntu-xenial

sincerely
-bino-

**Comment by moggers87** [comment]
I hit this same problem, it appears that node is not available for 32bit prebuilt. That's not something nodeenv can really solve, but it could give a nicer error (say with the URL that was tried)

**Comment by ekalinin** [comment]
Yeah, there's no 32-bit binary:

```bash
➜ curl -s https://nodejs.org/dist/v10.6.0/ | grep -o -P "node-v10.6.0-linux-[^\.]*" | sort | uniq
node-v10.6.0-linux-arm64
node-v10.6.0-linux-armv6l
node-v10.6.0-linux-armv7l
node-v10.6.0-linux-ppc64le
node-v10.6.0-linux-s390x
node-v10.6.0-linux-x64
```

@moggers87 thanks for help!
