### ISSUE TITLE
cspell package fails to install inside nodeenv but succeeds outside

### ISSUE THREAD

**Issue by ssbarnea** [ekalinin/nodeenv#221]
Initially I raised this bug at https://github.com/Jason3S/cspell/issues/53 but after it received a minor fix for `npm install -g .` command I am inclined to believe that this is a nodeenv specific bug now.

Reproducer:
```
pip install --user nodeenv
git clone https://github.com/Jason3S/cspell
cd cspell
nodeenv nenv
. nenv/bin/activate
npm install -g .
```

Be sure you run this on a clean clone, because otherwise if a build was performed and `dist/` folder was created and populated the install may succeed. Still, we need to be sure that installation would succeed without requiring extra preparatory steps, regardless of previous build being made inside the repository.

**Comment by ssbarnea** [comment]
Apparently I was able to find the bug in the package.json and raise PR at https://github.com/Jason3S/cspell/pull/57

**Comment by Jason3S** [comment]
There isn't an issue with the cspell package. It installs just fine. The problem is with trying to use the repository directly instead of using the npm package.

Why doesn't this work for you:
```
pip install --user nodeenv
nodeenv nenv
. nenv/bin/activate
npm install -g cspell
```

**Comment by ssbarnea** [comment]
@ekalinin Can you please have a look at https://github.com/Jason3S/cspell/issues/53 and give us a hand? 

I am not sure how to fix this issue where cspell does not install under noveenv because it is not compiled. We need to find a single step solution to this problem, one that would allow installation using  a git url, like `npm install git://...`.
