### ISSUE TITLE
Installation on Raspberry Pi 3 Model B fails with KeyError: 'armv8l'

### ISSUE THREAD

**Issue by carlodicelico** [ekalinin/nodeenv#227]
```
[main]      * Install prebuilt node (10.9.0)
[main]     Traceback (most recent call last):
[main]       File "/usr/src/app/c3po/bin/nodeenv", line 11, in <module>
[main]         sys.exit(main())
[main]       File "/usr/src/app/c3po/lib/python3.6/site-packages/nodeenv.py", line 1076, in main
[main]         create_environment(env_dir, opt)
[main]       File "/usr/src/app/c3po/lib/python3.6/site-packages/nodeenv.py", line 905, in create_environment
[main]         install_node(env_dir, src_dir, opt)
[main]       File "/usr/src/app/c3po/lib/python3.6/site-packages/nodeenv.py", line 686, in install_node
[main]         node_url = get_node_bin_url(opt.node)
[main]       File "/usr/src/app/c3po/lib/python3.6/site-packages/nodeenv.py", line 512, in get_node_bin_url
[main]         'arch': archmap[platform.machine()],
[main]     KeyError: 'armv8l'
```

Is this a matter of adding the arch to https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py#L499, or is there more to it?

**Comment by ekalinin** [comment]
Hi @carlodicelico 

> Is this a matter of adding the arch to https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py#L499, or is there more to it?

Yeah, it should be enough just to add a new entry in that dict.

PS:

arms supported by nodejs:

```
➜ curl -s https://nodejs.org/dist/latest/ | grep arm | awk '{print $2}' | grep -v "tar.xz"  | sort | uniq
href="node-v10.10.0-linux-arm64.tar.gz">node-v10.10.0-linux-arm64.tar.gz</a>
href="node-v10.10.0-linux-armv6l.tar.gz">node-v10.10.0-linux-armv6l.tar.gz</a>
href="node-v10.10.0-linux-armv7l.tar.gz">node-v10.10.0-linux-armv7l.tar.gz</a>
```

**Comment by carlodicelico** [comment]
Thanks!

Hmm... that's odd considering the 3 Model B has been around for quite some time (February 2016) and as far as I can tell, has always been the same architecture 🤔https://www.newegg.com/Product/Product.aspx?Item=N82E16813300007. I've run node on it myself, too. Looking into it more...

**Comment by carlodicelico** [comment]
Ah, I see—I think something is misconfigured in the Docker image I'm using. Not an issue with nodeenv, closing.

**Comment by carlodicelico** [comment]
Update for future wanderers: building from source via `--source` works perfectly, but increases container build time, obviously.

**Comment by carlodicelico** [comment]
So, the situation seems to be that the build servers used to build the Raspberry Pi Docker containers themselves use `armv8l`. I'm guessing that the value of the application container's `platform.machine()` (`uname -m`), which is `armv7l`, isn't the one being used by the subprocess created by the nodeenv installer, or something along those lines, and it's getting the build server's arch value, instead.

What I've done for now is [fork this repo and add a temporary mapping for armv8l to armv7l](https://github.com/carlodicelico/nodeenv/commit/8b5d59236e04127c698312589aaa3722a92c9e4b), and this causes nodeenv to install the right prebuilt node version for the target platform. I didn't do this as a PR because when nodejs supports armv8l, anyone using that temporary mapping will get broken builds, but wanted to add the band-aid fix here in case others have the same problem.

Another option would be to pre-compile the nodeenv binary on armv7l and add that to your repo, then `COPY` it to the right place in your Dockerfile. I went with the temporary mapping because it seems like the least amount of change later, since I can just update my requirements.txt and I'll be all set.
