### ISSUE TITLE
nodeenv error output for versions w/ a `v` prefix is suboptimal

### ISSUE THREAD

**Issue by jsoref** [ekalinin/nodeenv#235]
```
$ nodeenv --prebuilt  -n v10.15.2 node-v10.15.2
 * Install prebuilt node (v10.15.2) .Traceback (most recent call last):
```

Yes, the correct command should be `nodeenv --prebuilt  -n 10.15.2 node-v10.15.2`

I'm not interested in that. What bothers me is the `) .Traceback` output -- especially the apparently random placement of the `.`.

That currently comes from:
https://github.com/ekalinin/nodeenv/blob/a122f1857068d061e166c38b62640f6836efb3ef/nodeenv.py#L698
https://github.com/ekalinin/nodeenv/blob/a122f1857068d061e166c38b62640f6836efb3ef/nodeenv.py#L710
With the `Traceback` part being Python's standard traceback handling.

It seems to me that nodeenv could either handle this case gracefully (possibly by warning that it isn't expecting a `v` / or by explaining the 404 and providing the url it was looking at so someone could browse), or at the very least trap the exception and include a newline before spitting out `Traceback`....

Note that normally there are a bunch of `.`s as in:
```
$ nodeenv --prebuilt  -n 10.15.1 node-v10.15.1
 * Install prebuilt node (10.15.1) ..... done.
```
under which circumstances, the `.`s make sense as a form of progress. But for this early failure case, it just looks weird.

**Comment by ekalinin** [comment]
Fixed by #236
