### ISSUE TITLE
Feature: Store node_modules elsewhere

### ISSUE THREAD

**Issue by pykong** [ekalinin/nodeenv#237]
As a python developer, it drives me mad to have `node_modules` clutter my root folder. We do not put our python `site-packages` in there either but cleanly store them away elsewhere.

_I am not sure it is in the scope of `nodeenv` to address this problem however it would be great if it did._

What I envision would be a feature that stores the node_modules somewhere in the `.venv` folder at the same time conserving all path resolutions. Thereby we could continue to use any node command such as `npm install` just as before.

One package aiming to achieve that goal is:
https://github.com/shadow-light/npmenv

However, I would not like to have both `nodeenv` and `npmenv` meddle with my environments paths fearing that it eventually breaks. Also `npmenv` in its current incarnation does not store the `node_modules` in `.venv`.

Options of `node` itself that are not workable are:
- Setting the `NODE_PATH` env variable -> Works only for global installs, paths break
- Using the `--prefix` flag -> Does not save installs to `package.json`, paths break

**Comment by asottile** [comment]
If you use `nodeenv .nenv` + `npm install -g` it will store all of the modules inside `.nenv`:

(note: I'm only using `-n system` because my internet connection is abysmal right now)

```console
$ ~/opt/venv/bin/nodeenv nenv -n system
$ . nenv/bin/activate
$ npm install -g left-pad
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
+ left-pad@1.3.0
added 1 package from 1 contributor in 0.823s
$ ls -al
total 12
drwxr-xr-x  3 asottile asottile 4096 Dec 31 15:02 .
drwxrwxrwt 26 root     root     4096 Dec 31 15:02 ..
drwxr-xr-x  5 asottile asottile 4096 Dec 31 15:02 nenv
$ ls nenv/lib/node_modules/left-pad/
COPYING  index.d.ts  index.js  package.json  perf  README.md  test.js
```

**Comment by pykong** [comment]
@asottile Thanks for your response.
Let me try out your suggestion before closing this issue.

Let me say upfront that I usually tried:
`nodeenv -p` then use `npm install -g`

**Comment by pykong** [comment]
@asottile I can not install a node environment into a preexisting python virtual environment and then access globally installed javascript libraries from that environment for bundling.

It could well be that I am using any of the javascript bundling tools (browserify, webpack) wrong. However, it strikes me that `node_modules` are actually expected to sit at the root of your folder rather than in `lib/node_modules`.

Example sequence:

```sh
#  install and make nodeenv
mkdir nodeenv_plaground
cd nodeenv_plaground
# create and activate ve
python3 -m venv .venv
. .venv/bin/activate.fish
pip install nodeenv
nodeenv -p

# install js libs to .venv/lib/node_modules ...
npm install -g browserify jquery

# ... but those will not be found
echo "var $ = require('jquery');" >> bundle_me.js
browserify bundle_me.js -o bundle.js
```
Results in the following 
<details>
 <summary>Error message</summary>
  
  ```sh
Error: Cannot find module 'jquery' from '/home/ben/Projects/nodeenv_playground'
    at /home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/pykong/Projects/nodeenv_playground/.venv/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21)

  ```
</details>

**Comment by asottile** [comment]
I suspect `browserify` just doesn't support `-g` installs

**Comment by pykong** [comment]
Let me check with another bundler.

**Comment by pykong** [comment]
I have been able to successfully bundle a globally installed javascript dependency via [parcel](https://github.com/parcel-bundler/parcel). No `node_modules` folder was placed in my root as part of the process.

Hence, I do not think that `nodeenv` can or should do something about the issue.
Handling of import paths for javascript dependencies belong into javascript land and we should probably not mess with those from python land.

### (Crude) Example:
<details><summary>CLICK ME</summary>
<p>

**setup ve:**
```sh
#  install and make nodeenv
mkdir nodeenv_plaground
cd nodeenv_plaground
# create and activate ve
python3 -m venv .venv
. .venv/bin/activate.fish
pip install nodeenv
nodeenv -p

# install js libs to .venv/lib/node_modules ...
npm install -g parcel jquery
```

**index.html:**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My First Parcel App</title>
    <link rel="stylesheet" href="./styles.css" />
    <script src="./app.js"></script>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

**app.js:**
```js
import jquery from "jquery";
console.log(jquery);
```

**run in shell:**
```sh
parcel index.html
```

**result:**
- Bundles without error.
- Opening browser at given URL and checking console: jquery is there ;-)

</p>
</details>
