### ISSUE TITLE
Cannot install npm in Windows 10

### ISSUE THREAD

**Issue by ziong** [ekalinin/nodeenv#239]
when try to install with
`nodeenv --node=10.16.0 --npm=6.4.1 env`
I got the error "urllib.error.HTTPError: HTTP Error 404: Not Found"

seems that the zip file should have prefix "v"
my workaround:
i change the file nodeenv.py line 742 (inside **install_npm_win()**)
from 
`npm_url = 'https://github.com/npm/cli/archive/%s.zip' % opt.npm`
 to 
`npm_url = 'https://github.com/npm/cli/archive/v%s.zip' % opt.npm`

**Comment by Lucas-C** [comment]
This has been fixed by https://github.com/ekalinin/nodeenv/pull/233
