### ISSUE TITLE
Cannot install versions 1.3.4 or 1.3.5 if `no-binary=:all:` has been specified

### ISSUE THREAD

**Issue by moggers87** [ekalinin/nodeenv#251]
A wheel has been uploaded for 1.3.4 and 1.3.5, but not the sdists. If `no-binary=:all:` has been set in `pip.conf` or specified on the command line, pip will refuse to install anything later than nodenev 1.3.3.

A simple to solution is to upload both the wheel and the sdist rather than just one or the other.

Example pip output:

```
$ pip install --no-binary=:all: nodeenv==1.3.5
Collecting nodeenv==1.3.5
  Could not find a version that satisfies the requirement nodeenv==1.3.5 (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3)
No matching distribution found for nodeenv==1.3.5
$ pip install --no-binary=:none: nodeenv==1.3.5
Collecting nodeenv==1.3.5
  Downloading https://files.pythonhosted.org/packages/08/43/86ff33286c83f7b5e8903c32db01fe122c5e8a9d8dc1067dcaa9be54a033/nodeenv-1.3.5-py2.py3-none-any.whl
Installing collected packages: nodeenv
Successfully installed nodeenv-1.3.5
```

**Comment by fredvd** [comment]
We experienced this issue at a site where a pypi-mirror behind a firewall was used where the mirror which only accepts source distributions of packages, so the latest 1.3.5 'binary only' release would not be available at all.

**Comment by jgoldschrafe** [comment]
I'm experiencing this as well, where I can't build a Homebrew package using this as a source because of the wheel-only publishing.

**Comment by ekalinin** [comment]
Fixed. Please, check.

**Comment by chenrui333** [comment]
Thanks @ekalinin!!

**Comment by ekalinin** [comment]
Thanks all for patience and sorry for delay.
