### ISSUE TITLE
Replace `setuptools` runtime dependency with `packaging`

### ISSUE THREAD

**Issue by flying-sheep** [ekalinin/nodeenv#337]
You `import pkg_resources`, which is [deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html). For object oriented handling of versions, you should use [`packaging.version` ](https://packaging.pypa.io/en/stable/version.html) instead.

![grafik](https://github.com/ekalinin/nodeenv/assets/291575/b8f183bc-ff7d-4c4b-87a2-8199b4e98280)

**Comment by anisse** [comment]
In addition to the warning in the docs, it generates a warning in `requirements.txt` when using generating it with pip-compile :

```
# The following packages are considered to be unsafe in a requirements file:
setuptools==68.1.2 \
    --hash=sha256:3d4dfa6d95f1b101d695a6160a7626e15583af71a5f52176efa5d39a054d475d \
    --hash=sha256:3d8083eed2d13afc9426f227b24fd1659489ec107c0e86cec2ffdde5c92e790b
    # via nodeenv
```
