### ISSUE TITLE
Remove usage of `pipes`

### ISSUE THREAD

**Issue by bersbersbers** [ekalinin/nodeenv#341]
I am getting

> C:\Python\Lib\site-packages\nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13

due to 

https://github.com/ekalinin/nodeenv/blob/4ae75e3c3dfabee705405e0ef4e7459721fb17c4/nodeenv.py#L26

**Comment by bersbersbers** [comment]
Just came across another one:

> pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by eccles** [comment]
Same here - this occurred when I attempted to add support for python 3.12:

task: [check] ./scripts/builder.sh python3 -m pyright --stats archivist
/usr/local/lib/python3.12/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
/usr/local/lib/python3.12/site-packages/nodeenv.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
 * Install prebuilt node (21.0.0) .

The 'Install prebuilt node..'  hangs forever

**Comment by rffontenelle** [comment]
FWIW, it is deprecated [since Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#modules) and the [subprocess](https://docs.python.org/3/library/subprocess.html) module is the [recommended as replacement](https://peps.python.org/pep-0594/#deprecated-modules)
