### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by braindevices** [ekalinin/nodeenv#343]
site-packages/nodeenv.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

it looks like we are still using `from pkg_resources import parse_version`

please use packaging.version.parse or something similar

**Comment by neutrinoceros** [comment]
This is already fixed in `master`(see #338). What's missing is a release including the patch.

**Comment by taleinat** [comment]
> What's missing is a release including the patch.

Please consider releasing a new version, it's been 8 months since the last release and including this change would be welcome.

**Comment by ekalinin** [comment]
> @ekalinin, please consider publishing a new release, it's been over a year since the last release.

Hey, done!
