### ISSUE TITLE
Use prebuilt Node.js binaries instead of compiling

### ISSUE THREAD

**Issue by andreypopp** [ekalinin/nodeenv#56]
First, thank you for nodeenv. This is an awesome package and I just successfully integrated it into a deployment workflow which now contains python and npm packages.

What do you think if for those platforms there are nodejs prebuilt binaries available, nodeenv can just download them instead of building node from source? Mac OS X, Linux and Windows are [supported](http://nodejs.org/download/).

**Comment by pradyunsg** [comment]
I'm only here to say one thing: Thank you for doing this! ^>^
