### ISSUE TITLE
Add locally installed module's binaries to $PATH

### ISSUE THREAD

**Issue by jhermann** [ekalinin/nodeenv#86]
"activate" should add "‹envdir›/node_modules/.bin" to the $PATH, in front of "‹envdir›/bin".

**Comment by Jobava** [comment]
Hello, any progress on this issue?

How do people actually run nodeenv if the packages installed with npm are not in the PATH?

**Comment by jhermann** [comment]
A *local* install of gulp creates this, thus the original request:

    $ ls -l ./node_modules/.bin/gulp
    lrwxrwxrwx 1 jhe jhe 19 Jan 11 17:20 ./node_modules/.bin/gulp -> ../gulp/bin/gulp.js
