### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by sjml** [ekalinin/nodeenv#89]
It would be great if the `--python-virtualenv` option could also append the appropriate node commands to the `env/bin/activate.fish` as well as the plain `activate` script, so those using the [fish shell](http://fishshell.com/) could also benefit from a virtualenv + nodeenv combination. 

I'm still in the midst of learning the fish language myself, or this would come with a pull request, but wanted to enter it as an issue just in case it's something you could easily do. If not, I may come back in time with the code in hand.

**Comment by ejosvp** [comment]
+1

**Comment by epequeno** [comment]
:+1:

**Comment by MattSchlobohm** [comment]
+1

**Comment by alektrendak** [comment]
+1

**Comment by mwalercz** [comment]
+1

**Comment by tiberiuichim** [comment]
+1

**Comment by ekalinin** [comment]
A lot of thanks to @Terseus
