### ISSUE TITLE
logging fails with unicode chars

### ISSUE THREAD

**Issue by ttaghavi** [ekalinin/nodeenv#96]
Error traceback (last part):

File "/data/webadmin/.virtualenvs/ui/lib/python2.7/site-packages/nodeenv.py", line 144, in emit
    self.stream.write(fs % msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 42: ordinal not in range(128)

Since the encode/decode functions always confused me since I started using python, not sure what the best way would be to fix this.

What worked for me was:

self.stream.write(fs % msg.encode('utf8'))

But this will fail if msg is of type 'str'

**Comment by ralcini** [comment]
+1

**Comment by ralcini** [comment]
stream seems support only ascii strings, non ascii chars can be ignored or replaced with placeholder. What do you think? 

```
--- lib/python2.6/site-packages/nodeenv.py  2015-07-16 17:07:09.000000000 +0200
+++ lib/python2.6/site-packages/nodeenv.py  2015-07-16 17:08:07.344132749 +0200
@@ -152,7 +152,7 @@
     def emit(self, record):
         msg = self.format(record)
         fs = "%s" if getattr(record, "continued", False) else "%s\n"
-        self.stream.write(fs % msg)
+        self.stream.write(fs % msg.encode('ascii', 'ignore'))
         self.flush()
     logging.StreamHandler.emit = emit
```
