### ISSUE TITLE
Call deactivate_node from virtualenvwrapper's predeactivate hook

### ISSUE THREAD

**Issue by joemaller** [ekalinin/nodeenv#99]
Using nodeenv with virtualenvwrapper, I noticed that node's environment variables often spill out of their virtualenv. I found the `deactivate_node` command which got me wondering whether it'd be possible to integrate that into virtualenvwrapper's [predeactivate or postdeactivate hooks][hooks]?

[hooks]: http://virtualenvwrapper.readthedocs.org/en/latest/scripts.html#predeactivate

**Comment by Nirazul** [comment]
+1

**Comment by ekalinin** [comment]
Should be fixed. See #172
